library(arules)
library(arulesViz)
library(datasets)
library(data.table)
data("Groceries")
model= apriori(Groceries)
itemFrequencyPlot(Groceries)
itemFrequencyPlot(Groceries,support= 0.15)
itemFrequencyPlot(Groceries,topN= 20)
#implement apriori with support and confidence values
model1= apriori(Groceries,parameter = list(support= 0.01,confidence= 0.5))
inspect(model1)
plot(model1)
wholemilk= subset(model1,items %in% "whole milk")
inspect(wholemilk)
